name: Cachix

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  inputs:
    name: Push Inputs (${{ matrix.nixpkgs }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nixpkgs:
          - nixos-22.05
          - nixos-unstable
          - nixpkgs-unstable
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v17

      - name: Setup Cachix
        uses: cachix/cachix-action@v10
        with:
          name: ablescript
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Push Flake inputs
        run: nix flake archive --json --override-flake nixpkgs "github:NixOS/nixpkgs/${{ matrix.nixpkgs }}" | jq -r '.path,(.inputs | to_entries[].value.path)' | cachix push ablescript

  packages:
    name: Push Packages (${{ matrix.os }}:${{ matrix.nixpkgs }})
    runs-on: ${{ matrix.os }}
    needs:
      - inputs
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        nixpkgs:
          - nixos-22.05
          - nixos-unstable
          - nixpkgs-unstable
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v17

      - name: Setup Cachix
        uses: cachix/cachix-action@v10
        with:
          name: ablescript
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Push packages
        run: |
          for package in $(nix flake show --json | jq -r '.packages."x86_64-linux" | to_entries[].key'); do
            nix build --print-build-logs --json ".#${package}" --override-flake nixpkgs "github:NixOS/nixpkgs/${{ matrix.nixpkgs }}" | jq -r '.[].outputs | to_entries[].value' | cachix push ablescript
          done
